language: python
python:
  - "2.7"
  #- "3.3"
  #- "3.4"
before_install:
  - sudo apt-get install build-essential gfortran python-dev
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev 
  - sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
  - sudo apt-get install python-numpy 
  - sudo apt-get install python-scipy

# command to install dependencies
install:
  - easy_install -U setuptools
  - travis_wait pip install -r requirements.txt
  - pip install nose-exclude
  - pip install coveralls

# This is needed, otherwise, nosetests will import try to import wx.
before_script:
    - rm abipy/gui/__init__.py 
    - export LD_LIBRARY_PATH=/usr/lib/:$LD_LIBRARY_PATH

# command to run tests
script: nosetests
branches:
  only:
    - master
    - develop
#after_success:
#  coveralls
notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always



